### PR TITLE
Tweaks to README

### PR DESCRIPTION
**Pull request by AdrieanKhisbe**
Few tweaks to Readme :)

### CODE REVIEW

**Comment by AdrieanKhisbe** [comment]
`_` and `*` are the same

**Comment by AdrieanKhisbe** [comment]
oops. not in this context indeed. one query replace was of more

**Comment by franciscogouveia** [comment]
Great job again! :+1: Thanks

**Comment by AdrieanKhisbe** [comment]
you're welcome :)

**Comment by AdrieanKhisbe** [comment]
Was considering some refactoring, using lodash for instance.
So that after that code is more easily extensible.

What do you think about this?

**Pull request merged**
