### PR TITLE
Improved ci

### PR DESCRIPTION
**Pull request by AdrieanKhisbe**
setup coveralls and ci.

### CODE REVIEW

**Comment by franciscogouveia** [comment]
Thank you! This looks great

**Comment by AdrieanKhisbe** [comment]
you're welcome. :)

would you be interested to drop Grunt, to use a npm only build? :smiley:

**Comment by franciscogouveia** [comment]
Sounds good :) if npm can do it, grunt becomes obsolete. I would happily merge a PR on that. I will open an issue.

**Comment by AdrieanKhisbe** [comment]
great :)

**Comment by AdrieanKhisbe** [comment]
Few questions around:

- would you consider dropping support for node < 4 to use latest hapies&co
- would you accept using standard hapi style?

**Comment by AdrieanKhisbe** [comment]
(waiting your input for this :) )

**Comment by franciscogouveia** [comment]
> would you consider dropping support for node < 4 to use latest hapies&co?

Yes, definitely. We should encourage to move away from old node 0.x versions.

> would you accept using standard hapi style?

Not only accept, I want to :D

Thank you for your time and effort!

**Comment by AdrieanKhisbe** [comment]
You're welcome :)

**Comment by AdrieanKhisbe** [comment]
(by the way, could you log to coveralls.io to activate repo?)

**Pull request merged**
