### PR TITLE
Improved build

### PR DESCRIPTION
**Pull request by AdrieanKhisbe**
cf commit list

### CODE REVIEW

**Comment by AdrieanKhisbe** [comment]
(migration to es6 will be in a dedicated PR :) )

**Comment by AdrieanKhisbe** [comment]
voila :smiley:

**Comment by franciscogouveia** [comment]
Great job! :+1:

**Comment by AdrieanKhisbe** [comment]
Thanks =)
Le 8 janv. 2016 16:02, "Francisco Gouveia" <notifications@github.com> a
écrit :

**Pull request merged**
